<?php

use Illuminate\Database\Seeder;

class TeamsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('teams')->delete();
        
        \DB::table('teams')->insert(array (
            0 => 
            array (
                'id' => 1,
                'related_team_id' => NULL,
                'name' => 'DFK „Dainava“',
                'short_name' => 'DAI',
                'country' => 'Lietuva',
                'city' => 'Alytus',
                'phone_number' => '+370 612 61166',
                'email' => 'dfkdainava@gmail.com',
                'website' => 'http://www.dfkdainava.com',
                'address' => 'S. Dariaus ir S. Girėno g. 2-12, Alytus, LT-62137',
                'created_at' => '2020-04-26 12:55:17',
                'updated_at' => '2020-04-26 12:55:17',
                'current_tournament_id' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'related_team_id' => 1,
                'name' => 'DFK „Dainava B“',
                'short_name' => 'DAI',
                'country' => 'Lietuva',
                'city' => 'Alytus',
                'phone_number' => '+370 612 61166',
                'email' => 'dfkdainava@gmail.com',
                'website' => 'http://www.dfkdainava.com',
                'address' => 'S. Dariaus ir S. Girėno g. 2-12, Alytus, LT-62137',
                'created_at' => '2020-04-26 12:55:17',
                'updated_at' => '2020-04-26 12:55:17',
                'current_tournament_id' => 3,
            ),
            2 => 
            array (
                'id' => 3,
                'related_team_id' => NULL,
                'name' => 'FK „REO“',
                'short_name' => 'REO',
                'country' => 'Lietuva',
                'city' => 'Vilnius',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:03:06',
                'updated_at' => '2020-04-26 14:16:01',
                'current_tournament_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'related_team_id' => NULL,
                'name' => 'FK „Banga“',
                'short_name' => 'BAN',
                'country' => 'Lietuva',
                'city' => 'Gargždai',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:04:11',
                'updated_at' => '2020-04-26 14:16:30',
                'current_tournament_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'related_team_id' => NULL,
                'name' => 'FK „Atlantas“',
                'short_name' => 'ATL',
                'country' => 'Lietuva',
                'city' => 'Klaipėda',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:04:59',
                'updated_at' => '2020-04-26 14:17:06',
                'current_tournament_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'related_team_id' => NULL,
                'name' => 'FK „Kruoja“',
                'short_name' => 'KRU',
                'country' => 'Lietuva',
                'city' => 'Pakruojis',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:05:03',
                'updated_at' => '2020-04-26 14:17:54',
                'current_tournament_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'related_team_id' => NULL,
                'name' => 'FK „Sūduva“',
                'short_name' => 'SŪD',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:05:03',
                'updated_at' => '2020-04-26 13:05:03',
                'current_tournament_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'related_team_id' => NULL,
                'name' => 'FK „Ekranas“',
                'short_name' => 'EKR',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:05:05',
                'updated_at' => '2020-04-26 13:05:05',
                'current_tournament_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'related_team_id' => NULL,
                'name' => 'FK „Tauras“',
                'short_name' => 'TAU',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:05:05',
                'updated_at' => '2020-04-26 13:05:05',
                'current_tournament_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'related_team_id' => NULL,
                'name' => 'FK „Šiauliai“',
                'short_name' => 'ŠIA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:05:05',
                'updated_at' => '2020-04-26 13:05:05',
                'current_tournament_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'related_team_id' => NULL,
                'name' => 'FK „Žalgiris“',
                'short_name' => 'ŽAL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:05:05',
                'updated_at' => '2020-04-26 13:05:05',
                'current_tournament_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'related_team_id' => NULL,
                'name' => 'FK „Klaipėdos Granitas“',
                'short_name' => 'KLA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:08:24',
                'updated_at' => '2020-04-26 13:08:24',
                'current_tournament_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'related_team_id' => NULL,
                'name' => 'FK „Riteriai“',
                'short_name' => 'RIT',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:08:28',
                'updated_at' => '2020-04-26 14:12:02',
                'current_tournament_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'related_team_id' => NULL,
                'name' => 'FK „Hegelmann Litauen“',
                'short_name' => 'HEG',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:10:20',
                'updated_at' => '2020-04-26 13:10:20',
                'current_tournament_id' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'related_team_id' => NULL,
                'name' => 'FK „Šilas“',
                'short_name' => 'ŠIL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:10:20',
                'updated_at' => '2020-04-26 13:10:20',
                'current_tournament_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'related_team_id' => NULL,
                'name' => 'FK „Druskininkai“',
                'short_name' => 'DRU',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:10:21',
                'updated_at' => '2020-04-26 13:10:21',
                'current_tournament_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'related_team_id' => NULL,
                'name' => 'FK „Rūdupis“',
                'short_name' => 'RŪD',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:12:08',
                'updated_at' => '2020-04-26 13:12:08',
                'current_tournament_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'related_team_id' => NULL,
                'name' => 'FK „Sūduva B“',
                'short_name' => 'SŪD',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:12:18',
                'updated_at' => '2020-04-26 13:12:18',
                'current_tournament_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'related_team_id' => NULL,
                'name' => 'FK „Šilas B“',
                'short_name' => 'ŠIL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:13:10',
                'updated_at' => '2020-04-26 13:13:10',
                'current_tournament_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'related_team_id' => NULL,
                'name' => 'FK „Sveikata“',
                'short_name' => 'SVE',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:13:17',
                'updated_at' => '2020-04-26 13:13:17',
                'current_tournament_id' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'related_team_id' => NULL,
                'name' => 'FK „Lietava B“',
                'short_name' => 'LIE',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:13:17',
                'updated_at' => '2020-04-26 13:13:17',
                'current_tournament_id' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'related_team_id' => NULL,
                'name' => 'FK „Spyris B“',
                'short_name' => 'SPY',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:13:20',
                'updated_at' => '2020-04-26 13:13:20',
                'current_tournament_id' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'related_team_id' => NULL,
                'name' => 'FK „SRC-Vidzgiris“',
                'short_name' => 'SRC',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:13:21',
                'updated_at' => '2020-04-26 13:13:21',
                'current_tournament_id' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'related_team_id' => NULL,
                'name' => 'FK „Atmosfera“',
                'short_name' => 'ATM',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:13:58',
                'updated_at' => '2020-04-26 13:13:58',
                'current_tournament_id' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'related_team_id' => NULL,
                'name' => 'FK „Vilniaus Vytis“',
                'short_name' => 'VIL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:19',
                'updated_at' => '2020-04-26 13:14:19',
                'current_tournament_id' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'related_team_id' => NULL,
                'name' => 'FK „Vilnius“',
                'short_name' => 'VIL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:21',
                'updated_at' => '2020-04-26 13:14:21',
                'current_tournament_id' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'related_team_id' => NULL,
                'name' => 'FK „Pakruojis“',
                'short_name' => 'PAK',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:26',
                'updated_at' => '2020-04-26 13:14:26',
                'current_tournament_id' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'related_team_id' => NULL,
                'name' => 'FA „Šiauliai“',
                'short_name' => 'FAŠ',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:28',
                'updated_at' => '2020-04-26 14:14:11',
                'current_tournament_id' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'related_team_id' => NULL,
                'name' => 'FK „Žalgiris B“',
                'short_name' => 'ŽAL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:29',
                'updated_at' => '2020-04-26 13:14:29',
                'current_tournament_id' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'related_team_id' => NULL,
                'name' => 'FK „Minija“',
                'short_name' => 'MIN',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:29',
                'updated_at' => '2020-04-26 13:14:29',
                'current_tournament_id' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'related_team_id' => NULL,
                'name' => 'FK „Džiugas“',
                'short_name' => 'DŽI',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:31',
                'updated_at' => '2020-04-26 13:14:31',
                'current_tournament_id' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'related_team_id' => NULL,
                'name' => 'FK „Jonava“',
                'short_name' => 'JON',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:33',
                'updated_at' => '2020-04-26 13:14:33',
                'current_tournament_id' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'related_team_id' => NULL,
                'name' => 'FK „Riteriai B“',
                'short_name' => 'RIT',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:33',
                'updated_at' => '2020-04-26 13:14:33',
                'current_tournament_id' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'related_team_id' => NULL,
                'name' => 'FK „Kupiškis“',
                'short_name' => 'KUP',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:14:33',
                'updated_at' => '2020-04-26 13:14:33',
                'current_tournament_id' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'related_team_id' => NULL,
                'name' => 'FK „Nevėžis“',
                'short_name' => 'NEV',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:15:18',
                'updated_at' => '2020-04-26 13:15:18',
                'current_tournament_id' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'related_team_id' => NULL,
                'name' => 'FK „Stumbras B“',
                'short_name' => 'STU',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:16:01',
                'updated_at' => '2020-04-26 13:16:01',
                'current_tournament_id' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'related_team_id' => NULL,
                'name' => 'FK „Panevėžys“',
                'short_name' => 'PAN',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:16:22',
                'updated_at' => '2020-04-26 13:16:22',
                'current_tournament_id' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'related_team_id' => NULL,
                'name' => 'FK „Koralas“',
                'short_name' => 'KOR',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:16:32',
                'updated_at' => '2020-04-26 13:16:32',
                'current_tournament_id' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'related_team_id' => NULL,
                'name' => 'FK „NFA“',
                'short_name' => 'NFA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:16:34',
                'updated_at' => '2020-04-26 13:16:34',
                'current_tournament_id' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'related_team_id' => NULL,
                'name' => 'FK „Utenis“',
                'short_name' => 'UTE',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:16:37',
                'updated_at' => '2020-04-26 13:16:37',
                'current_tournament_id' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'related_team_id' => NULL,
                'name' => 'FK „Palanga“',
                'short_name' => 'PAL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:18:11',
                'updated_at' => '2020-04-26 13:18:11',
                'current_tournament_id' => NULL,
            ),
            41 => 
            array (
                'id' => 43,
                'related_team_id' => NULL,
                'name' => 'FK „Šilutė“',
                'short_name' => 'ŠIL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:18:32',
                'updated_at' => '2020-04-26 13:18:32',
                'current_tournament_id' => NULL,
            ),
            42 => 
            array (
                'id' => 44,
                'related_team_id' => NULL,
                'name' => 'FK „Utenis B“',
                'short_name' => 'UTE',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:18:41',
                'updated_at' => '2020-04-26 13:18:41',
                'current_tournament_id' => NULL,
            ),
            43 => 
            array (
                'id' => 45,
                'related_team_id' => NULL,
                'name' => 'FBK „Kaunas“',
                'short_name' => 'FBK',
                'country' => 'Lietuva',
                'city' => 'Kaunas',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:23:24',
                'updated_at' => '2020-04-26 14:14:36',
                'current_tournament_id' => NULL,
            ),
            44 => 
            array (
                'id' => 46,
                'related_team_id' => NULL,
                'name' => 'FK „Kražantė“',
                'short_name' => 'KRA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:23:27',
                'updated_at' => '2020-04-26 13:23:27',
                'current_tournament_id' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'related_team_id' => NULL,
                'name' => 'FK „Lokomotyvas“',
                'short_name' => 'LOK',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:23:27',
                'updated_at' => '2020-04-26 13:23:27',
                'current_tournament_id' => NULL,
            ),
            46 => 
            array (
                'id' => 48,
                'related_team_id' => NULL,
                'name' => 'FK „Ekranas B“',
                'short_name' => 'EKR',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:24:59',
                'updated_at' => '2020-04-26 13:24:59',
                'current_tournament_id' => NULL,
            ),
            47 => 
            array (
                'id' => 49,
                'related_team_id' => NULL,
                'name' => 'FK „Kruoja B“',
                'short_name' => 'KRU',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:26:07',
                'updated_at' => '2020-04-26 13:26:07',
                'current_tournament_id' => NULL,
            ),
            48 => 
            array (
                'id' => 50,
                'related_team_id' => NULL,
                'name' => 'FK „Banga B“',
                'short_name' => 'BAN',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:27:34',
                'updated_at' => '2020-04-26 13:27:34',
                'current_tournament_id' => NULL,
            ),
            49 => 
            array (
                'id' => 51,
                'related_team_id' => NULL,
                'name' => 'FK „Šiauliai B“',
                'short_name' => 'ŠIA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:29:13',
                'updated_at' => '2020-04-26 13:29:13',
                'current_tournament_id' => NULL,
            ),
            50 => 
            array (
                'id' => 52,
                'related_team_id' => NULL,
                'name' => 'FK „Tauras B“',
                'short_name' => 'TAU',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:29:15',
                'updated_at' => '2020-04-26 13:29:15',
                'current_tournament_id' => NULL,
            ),
            51 => 
            array (
                'id' => 53,
                'related_team_id' => NULL,
                'name' => 'FK „Atlantas B“',
                'short_name' => 'ATL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:29:29',
                'updated_at' => '2020-04-26 13:29:29',
                'current_tournament_id' => NULL,
            ),
            52 => 
            array (
                'id' => 54,
                'related_team_id' => NULL,
                'name' => 'FK „Klaipėdos Granitas B“',
                'short_name' => 'KLA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:29:59',
                'updated_at' => '2020-04-26 14:14:47',
                'current_tournament_id' => NULL,
            ),
            53 => 
            array (
                'id' => 55,
                'related_team_id' => NULL,
                'name' => 'FM „Ateitis“',
                'short_name' => 'FMA',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:33:50',
                'updated_at' => '2020-04-26 14:15:24',
                'current_tournament_id' => NULL,
            ),
            54 => 
            array (
                'id' => 56,
                'related_team_id' => NULL,
                'name' => 'FK „Nevėžis B“',
                'short_name' => 'NEV',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:34:57',
                'updated_at' => '2020-04-26 13:34:57',
                'current_tournament_id' => NULL,
            ),
            55 => 
            array (
                'id' => 57,
                'related_team_id' => NULL,
                'name' => 'FK „Jonava B“',
                'short_name' => 'JON',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:35:06',
                'updated_at' => '2020-04-26 13:35:06',
                'current_tournament_id' => NULL,
            ),
            56 => 
            array (
                'id' => 58,
                'related_team_id' => NULL,
                'name' => 'FK „Kauno Žalgiris B“',
                'short_name' => 'KAU',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:35:08',
                'updated_at' => '2020-04-26 13:35:08',
                'current_tournament_id' => NULL,
            ),
            57 => 
            array (
                'id' => 59,
                'related_team_id' => NULL,
                'name' => 'FK „Tera“',
                'short_name' => 'TER',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:36:13',
                'updated_at' => '2020-04-26 13:36:13',
                'current_tournament_id' => NULL,
            ),
            58 => 
            array (
                'id' => 60,
                'related_team_id' => NULL,
                'name' => 'FK „Baltijos Futbolo Akademija“',
                'short_name' => 'BAL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:36:22',
                'updated_at' => '2020-04-26 13:36:22',
                'current_tournament_id' => NULL,
            ),
            59 => 
            array (
                'id' => 61,
                'related_team_id' => NULL,
                'name' => 'FK „Viltis“',
                'short_name' => 'VIL',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:36:28',
                'updated_at' => '2020-04-26 13:36:28',
                'current_tournament_id' => NULL,
            ),
            60 => 
            array (
                'id' => 62,
                'related_team_id' => NULL,
                'name' => 'FK „Panerys“',
                'short_name' => 'PAN',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:36:32',
                'updated_at' => '2020-04-26 13:36:32',
                'current_tournament_id' => NULL,
            ),
            61 => 
            array (
                'id' => 63,
                'related_team_id' => NULL,
                'name' => 'FK „Lygis“',
                'short_name' => 'LYG',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:39:29',
                'updated_at' => '2020-04-26 13:39:29',
                'current_tournament_id' => NULL,
            ),
            62 => 
            array (
                'id' => 64,
                'related_team_id' => NULL,
                'name' => 'FK „Prienai“',
                'short_name' => 'PRI',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:39:38',
                'updated_at' => '2020-04-26 13:39:38',
                'current_tournament_id' => NULL,
            ),
            63 => 
            array (
                'id' => 65,
                'related_team_id' => NULL,
                'name' => 'FA „Dainava“',
                'short_name' => 'FAD',
                'country' => 'Lietuva',
                'city' => '-',
                'phone_number' => NULL,
                'email' => NULL,
                'website' => NULL,
                'address' => NULL,
                'created_at' => '2020-04-26 13:39:52',
                'updated_at' => '2020-04-26 14:14:57',
                'current_tournament_id' => NULL,
            ),
        ));
        
        
    }
}